// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSrhzhXfPKJemo--M1eNIPLDNWBZdg9nQ',
    appId: '1:489610860756:web:3f761cdef83e19c8788341',
    messagingSenderId: '489610860756',
    projectId: 'lebanes-embassy',
    authDomain: 'lebanes-embassy.firebaseapp.com',
    storageBucket: 'lebanes-embassy.firebasestorage.app',
    measurementId: 'G-9WL39X7JJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB339RzdgxTtTVe4T5zHlzyWS21lu9kKqM',
    appId: '1:489610860756:android:7b2d61df05356b84788341',
    messagingSenderId: '489610860756',
    projectId: 'lebanes-embassy',
    storageBucket: 'lebanes-embassy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO1NWVhiuio5Q3lWMRmOnVKC0Bdwxx3JM',
    appId: '1:489610860756:ios:e3e942633e9e0aed788341',
    messagingSenderId: '489610860756',
    projectId: 'lebanes-embassy',
    storageBucket: 'lebanes-embassy.firebasestorage.app',
    iosBundleId: 'com.lebanes.embassy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO1NWVhiuio5Q3lWMRmOnVKC0Bdwxx3JM',
    appId: '1:489610860756:ios:47af41a1848c914f788341',
    messagingSenderId: '489610860756',
    projectId: 'lebanes-embassy',
    storageBucket: 'lebanes-embassy.firebasestorage.app',
    iosBundleId: 'com.example.todoapp.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSrhzhXfPKJemo--M1eNIPLDNWBZdg9nQ',
    appId: '1:489610860756:web:46d89eab23844ff4788341',
    messagingSenderId: '489610860756',
    projectId: 'lebanes-embassy',
    authDomain: 'lebanes-embassy.firebaseapp.com',
    storageBucket: 'lebanes-embassy.firebasestorage.app',
    measurementId: 'G-KQMDQBRBB7',
  );

}